<?php

namespace Database\Seeders;

use App\Models\Activity;
use App\Models\AiMatch;
use App\Models\ArtistProfile;
use App\Models\City;
use App\Models\Collective;
use App\Models\District;
use App\Models\Event;
use App\Models\LiveRoom;
use App\Models\OpenCall;
use App\Models\Space;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        Model::unguarded(function (): void {
            $now = Carbon::now('Europe/Rome');

            $city = City::updateOrCreate(
                ['slug' => 'rome'],
                [
                    'name' => 'Rome',
                    'country' => 'Italy',
                    'timezone' => 'Europe/Rome',
                    'ambient_color' => '#8B5CFF',
                    'accent_color' => '#FF3D8B',
                    'is_active' => true,
                ],
            );

            $districts = collect([
                ['name' => 'San Lorenzo', 'slug' => 'san-lorenzo', 'tone' => 'audio', 'map_x' => 32, 'map_y' => 42],
                ['name' => 'Ostiense', 'slug' => 'ostiense', 'tone' => 'events', 'map_x' => 56, 'map_y' => 56],
                ['name' => 'Pigneto', 'slug' => 'pigneto', 'tone' => 'spaces', 'map_x' => 78, 'map_y' => 34],
                ['name' => 'Trastevere', 'slug' => 'trastevere', 'tone' => 'artists', 'map_x' => 42, 'map_y' => 68],
                ['name' => 'Testaccio', 'slug' => 'testaccio', 'tone' => 'collectives', 'map_x' => 72, 'map_y' => 62],
                ['name' => 'Monti', 'slug' => 'monti', 'tone' => 'artists', 'map_x' => 48, 'map_y' => 32],
            ])->mapWithKeys(fn (array $district) => [
                $district['slug'] => District::updateOrCreate(
                    ['city_id' => $city->id, 'slug' => $district['slug']],
                    [
                        'name' => $district['name'],
                        'tone' => $district['tone'],
                        'map_x' => $district['map_x'],
                        'map_y' => $district['map_y'],
                        'description' => "{$district['name']} creative scene",
                        'is_active' => true,
                    ],
                ),
            ]);

            $users = collect([
                ['name' => 'Luca Moretti', 'email' => 'luca@novera.test'],
                ['name' => 'Alba Forma', 'email' => 'alba@novera.test'],
                ['name' => 'Neri Luce', 'email' => 'neri@novera.test'],
                ['name' => 'Riva Ensemble', 'email' => 'riva@novera.test'],
            ])->mapWithKeys(fn (array $user) => [
                $user['email'] => User::updateOrCreate(
                    ['email' => $user['email']],
                    [
                        'name' => $user['name'],
                        'password' => Hash::make('password'),
                    ],
                ),
            ]);

            $saveArtistProfile = function (array $lookup, array $attributes): ArtistProfile {
                $profile = ArtistProfile::firstOrNew($lookup);
                $profile->mergeCasts([
                    'tags' => 'array',
                    'links' => 'array',
                    'skills' => 'array',
                    'is_featured' => 'boolean',
                    'is_active' => 'boolean',
                ]);
                $profile->forceFill($attributes)->save();

                return $profile->refresh();
            };

            $profiles = collect([
                'luca-moretti' => $saveArtistProfile(
                    ['slug' => 'luca-moretti'],
                    [
                        'user_id' => $users['luca@novera.test']->id,
                        'city_id' => $city->id,
                        'district_id' => $districts['san-lorenzo']->id,
                        'display_name' => 'Luca Moretti',
                        'bio' => 'Visual artist working with projection, stage atmospheres, and site-responsive installations.',
                        'discipline' => 'Visual artist',
                        'status' => 'available',
                        'availability' => 'available tonight',
                        'tags' => ['visual', 'installation', 'projection'],
                        'links' => ['https://luca.novera.test'],
                        'skills' => ['creative direction', 'projection mapping', 'stage visuals'],
                        'profile_score' => 72,
                        'is_featured' => true,
                        'is_active' => true,
                    ],
                ),
                'alba-forma' => $saveArtistProfile(
                    ['slug' => 'alba-forma'],
                    [
                        'user_id' => $users['alba@novera.test']->id,
                        'city_id' => $city->id,
                        'district_id' => $districts['ostiense']->id,
                        'display_name' => 'Alba Forma',
                        'bio' => 'Sound artist collecting Rome field recordings and shaping spatial listening sessions.',
                        'discipline' => 'Sound artist',
                        'status' => 'live now',
                        'availability' => 'live room active',
                        'tags' => ['sound', 'field recording', 'spatial audio'],
                        'links' => ['https://alba.novera.test'],
                        'skills' => ['sound design', 'field recording', 'live performance'],
                        'profile_score' => 91,
                        'is_featured' => true,
                        'is_active' => true,
                    ],
                ),
                'neri-luce' => $saveArtistProfile(
                    ['slug' => 'neri-luce'],
                    [
                        'user_id' => $users['neri@novera.test']->id,
                        'city_id' => $city->id,
                        'district_id' => $districts['pigneto']->id,
                        'display_name' => 'Neri Luce',
                        'bio' => 'Moving-image artist editing archival fragments, 16mm textures, and night footage.',
                        'discipline' => 'Moving image',
                        'status' => 'open to collab',
                        'availability' => 'weekends',
                        'tags' => ['film', 'moving image', 'editing'],
                        'links' => ['https://neri.novera.test'],
                        'skills' => ['editing', 'color grading', '16mm'],
                        'profile_score' => 84,
                        'is_featured' => false,
                        'is_active' => true,
                    ],
                ),
                'riva-ensemble' => $saveArtistProfile(
                    ['slug' => 'riva-ensemble'],
                    [
                        'user_id' => $users['riva@novera.test']->id,
                        'city_id' => $city->id,
                        'district_id' => $districts['trastevere']->id,
                        'display_name' => 'Riva Ensemble',
                        'bio' => 'Performance collective building body-led scores for courtyards, galleries, and river edges.',
                        'discipline' => 'Performance collective',
                        'status' => 'recruiting',
                        'availability' => 'by invite',
                        'tags' => ['performance', 'collective', 'body'],
                        'links' => ['https://riva.novera.test'],
                        'skills' => ['performance', 'movement', 'live direction'],
                        'profile_score' => 79,
                        'is_featured' => false,
                        'is_active' => true,
                    ],
                ),
            ]);

            $spaces = collect([
                'forma-cinema' => Space::updateOrCreate(
                    ['city_id' => $city->id, 'slug' => 'forma-cinema'],
                    [
                        'district_id' => $districts['ostiense']->id,
                        'owner_id' => $users['alba@novera.test']->id,
                        'name' => 'Forma Cinema',
                        'type' => 'cinema',
                        'description' => 'A former neighborhood cinema tuned for screenings, talks, and spatial audio sessions.',
                        'image' => '/images/spaces/forma-cinema.jpg',
                        'address' => 'Via Ostiense 122, Rome',
                        'latitude' => 41.8719000,
                        'longitude' => 12.4803000,
                        'status' => 'available tonight',
                        'capacity' => 120,
                        'amenities' => ['screen', 'surround audio', 'projector'],
                        'tags' => ['screening', 'audio', 'cinema'],
                        'is_featured' => true,
                        'is_active' => true,
                    ],
                ),
                'cava-studio' => Space::updateOrCreate(
                    ['city_id' => $city->id, 'slug' => 'cava-studio'],
                    [
                        'district_id' => $districts['san-lorenzo']->id,
                        'owner_id' => $users['luca@novera.test']->id,
                        'name' => 'Cava Studio',
                        'type' => 'studio',
                        'description' => 'Flexible studio for projection tests, small performances, and live-score rehearsals.',
                        'image' => '/images/spaces/cava-studio.jpg',
                        'address' => 'Via dei Volsci 44, Rome',
                        'latitude' => 41.8995000,
                        'longitude' => 12.5183000,
                        'status' => 'open call',
                        'capacity' => 40,
                        'amenities' => ['dmx lights', 'black box', 'audio desk'],
                        'tags' => ['projection', 'studio', 'dmx'],
                        'is_featured' => true,
                        'is_active' => true,
                    ],
                ),
                'pigneto-archive' => Space::updateOrCreate(
                    ['city_id' => $city->id, 'slug' => 'pigneto-archive'],
                    [
                        'district_id' => $districts['pigneto']->id,
                        'owner_id' => $users['neri@novera.test']->id,
                        'name' => 'Pigneto Archive',
                        'type' => 'gallery',
                        'description' => 'A compact archive and gallery for moving-image studies and experimental screenings.',
                        'image' => '/images/spaces/pigneto-archive.jpg',
                        'address' => 'Via del Pigneto 88, Rome',
                        'latitude' => 41.8883000,
                        'longitude' => 12.5297000,
                        'status' => 'viewing slots',
                        'capacity' => 60,
                        'amenities' => ['archive tables', '16mm projector', 'listening bench'],
                        'tags' => ['archive', 'gallery', 'moving image'],
                        'is_featured' => false,
                        'is_active' => true,
                    ],
                ),
            ]);

            $collectives = collect([
                'echoes-of-now' => Collective::updateOrCreate(
                    ['slug' => 'echoes-of-now'],
                    [
                        'city_id' => $city->id,
                        'district_id' => $districts['testaccio']->id,
                        'owner_id' => $users['alba@novera.test']->id,
                        'name' => 'Echoes Of Now',
                        'description' => 'An audio-visual collective mapping Rome night culture through sound, image, and gathering.',
                        'discipline' => 'Audio / visual',
                        'image' => '/images/collectives/echoes-of-now.jpg',
                        'cover_image' => '/images/collectives/echoes-of-now-cover.jpg',
                        'members_count' => 18,
                        'recruiting_status' => 'recruiting',
                        'tags' => ['audio', 'visual', 'night culture'],
                        'links' => ['https://echoes.novera.test'],
                        'is_featured' => true,
                        'is_active' => true,
                    ],
                ),
                'afterlight-studies' => Collective::updateOrCreate(
                    ['slug' => 'afterlight-studies'],
                    [
                        'city_id' => $city->id,
                        'district_id' => $districts['pigneto']->id,
                        'owner_id' => $users['neri@novera.test']->id,
                        'name' => 'Afterlight Studies',
                        'description' => 'A small image circle focused on 16mm, projection, and shared screening formats.',
                        'discipline' => '16mm / image',
                        'image' => '/images/collectives/afterlight-studies.jpg',
                        'cover_image' => '/images/collectives/afterlight-studies-cover.jpg',
                        'members_count' => 7,
                        'recruiting_status' => 'open to collab',
                        'tags' => ['film', 'image', 'screening'],
                        'links' => ['https://afterlight.novera.test'],
                        'is_featured' => false,
                        'is_active' => true,
                    ],
                ),
                'courtyard-resonance' => Collective::updateOrCreate(
                    ['slug' => 'courtyard-resonance'],
                    [
                        'city_id' => $city->id,
                        'district_id' => $districts['san-lorenzo']->id,
                        'owner_id' => $users['riva@novera.test']->id,
                        'name' => 'Courtyard Resonance',
                        'description' => 'Live sound makers staging intimate performance scores in courtyards and studios.',
                        'discipline' => 'Live sound',
                        'image' => '/images/collectives/courtyard-resonance.jpg',
                        'cover_image' => '/images/collectives/courtyard-resonance-cover.jpg',
                        'members_count' => 12,
                        'recruiting_status' => 'invite only',
                        'tags' => ['sound', 'performance', 'listening'],
                        'links' => ['https://courtyard.novera.test'],
                        'is_featured' => true,
                        'is_active' => true,
                    ],
                ),
            ]);

            $events = collect([
                'ruins-in-frequency' => Event::updateOrCreate(
                    ['city_id' => $city->id, 'slug' => 'ruins-in-frequency'],
                    [
                        'district_id' => $districts['ostiense']->id,
                        'space_id' => $spaces['forma-cinema']->id,
                        'collective_id' => $collectives['echoes-of-now']->id,
                        'organizer_id' => $users['alba@novera.test']->id,
                        'title' => 'Ruins in Frequency',
                        'description' => 'A spatial audio listening session built from industrial field recordings around Ostiense.',
                        'type' => 'listening session',
                        'image' => '/images/events/ruins-in-frequency.jpg',
                        'cover_image' => '/images/events/ruins-in-frequency-cover.jpg',
                        'starts_at' => $now->copy()->setTime(21, 30),
                        'ends_at' => $now->copy()->setTime(23, 0),
                        'timezone' => 'Europe/Rome',
                        'location_name' => 'Forma Cinema',
                        'address' => 'Via Ostiense 122, Rome',
                        'status' => 'scheduled',
                        'capacity' => 120,
                        'attendees_count' => 36,
                        'tags' => ['spatial audio', 'field recording'],
                        'is_featured' => true,
                        'is_active' => true,
                    ],
                ),
                'afterlight-studies-event' => Event::updateOrCreate(
                    ['city_id' => $city->id, 'slug' => 'afterlight-studies-event'],
                    [
                        'district_id' => $districts['pigneto']->id,
                        'space_id' => $spaces['pigneto-archive']->id,
                        'collective_id' => $collectives['afterlight-studies']->id,
                        'organizer_id' => $users['neri@novera.test']->id,
                        'title' => 'Afterlight Studies',
                        'description' => 'A compact screening of 16mm fragments, notes, and rough assemblies.',
                        'type' => 'screening',
                        'image' => '/images/events/afterlight-studies.jpg',
                        'cover_image' => '/images/events/afterlight-studies-cover.jpg',
                        'starts_at' => $now->copy()->setTime(20, 0),
                        'ends_at' => $now->copy()->setTime(21, 45),
                        'timezone' => 'Europe/Rome',
                        'location_name' => 'Pigneto Archive',
                        'address' => 'Via del Pigneto 88, Rome',
                        'status' => 'scheduled',
                        'capacity' => 60,
                        'attendees_count' => 22,
                        'tags' => ['16mm', 'moving image'],
                        'is_featured' => true,
                        'is_active' => true,
                    ],
                ),
                'courtyard-resonance-event' => Event::updateOrCreate(
                    ['city_id' => $city->id, 'slug' => 'courtyard-resonance-event'],
                    [
                        'district_id' => $districts['san-lorenzo']->id,
                        'space_id' => $spaces['cava-studio']->id,
                        'collective_id' => $collectives['courtyard-resonance']->id,
                        'organizer_id' => $users['riva@novera.test']->id,
                        'title' => 'Courtyard Resonance',
                        'description' => 'Live sound and body-led performance unfolding across studio corners.',
                        'type' => 'performance',
                        'image' => '/images/events/courtyard-resonance.jpg',
                        'cover_image' => '/images/events/courtyard-resonance-cover.jpg',
                        'starts_at' => $now->copy()->setTime(23, 15),
                        'ends_at' => $now->copy()->addDay()->setTime(0, 30),
                        'timezone' => 'Europe/Rome',
                        'location_name' => 'Cava Studio',
                        'address' => 'Via dei Volsci 44, Rome',
                        'status' => 'live',
                        'capacity' => 40,
                        'attendees_count' => 31,
                        'tags' => ['live sound', 'performance'],
                        'is_featured' => true,
                        'is_active' => true,
                    ],
                ),
                'body-index' => Event::updateOrCreate(
                    ['city_id' => $city->id, 'slug' => 'body-index'],
                    [
                        'district_id' => $districts['trastevere']->id,
                        'space_id' => null,
                        'collective_id' => null,
                        'organizer_id' => $users['riva@novera.test']->id,
                        'title' => 'Body Index',
                        'description' => 'A performance score tracing gestures, river movement, and shared notation.',
                        'type' => 'performance',
                        'image' => '/images/events/body-index.jpg',
                        'cover_image' => '/images/events/body-index-cover.jpg',
                        'starts_at' => $now->copy()->addDay()->setTime(19, 0),
                        'ends_at' => $now->copy()->addDay()->setTime(20, 30),
                        'timezone' => 'Europe/Rome',
                        'location_name' => 'Trastevere courtyard',
                        'address' => 'Trastevere, Rome',
                        'status' => 'scheduled',
                        'capacity' => 50,
                        'attendees_count' => 14,
                        'tags' => ['performance', 'movement'],
                        'is_featured' => false,
                        'is_active' => true,
                    ],
                ),
            ]);

            $liveRooms = collect([
                'travertine-echoes' => LiveRoom::updateOrCreate(
                    ['city_id' => $city->id, 'slug' => 'travertine-echoes'],
                    [
                        'district_id' => $districts['ostiense']->id,
                        'host_id' => $users['alba@novera.test']->id,
                        'artist_profile_id' => $profiles['alba-forma']->id,
                        'event_id' => $events['ruins-in-frequency']->id,
                        'space_id' => $spaces['forma-cinema']->id,
                        'title' => 'Travertine Echoes',
                        'description' => 'Live room for dusk recordings and acoustic notes from a disused cinema.',
                        'topic' => 'Recorded at dusk in a disused cinema',
                        'image' => '/images/live-rooms/travertine-echoes.jpg',
                        'status' => 'live',
                        'listeners_count' => 42,
                        'speakers_count' => 3,
                        'started_at' => $now->copy()->subMinutes(48),
                        'ended_at' => null,
                        'audio_url' => '/audio/travertine-echoes.mp3',
                        'waveform' => [12, 24, 18, 38, 44, 29, 56, 42, 35, 60, 48, 33],
                        'tags' => ['field recording', 'cinema', 'spatial audio'],
                        'is_featured' => true,
                        'is_active' => true,
                    ],
                ),
                'courtyard-signal' => LiveRoom::updateOrCreate(
                    ['city_id' => $city->id, 'slug' => 'courtyard-signal'],
                    [
                        'district_id' => $districts['san-lorenzo']->id,
                        'host_id' => $users['luca@novera.test']->id,
                        'artist_profile_id' => $profiles['luca-moretti']->id,
                        'event_id' => $events['courtyard-resonance-event']->id,
                        'space_id' => $spaces['cava-studio']->id,
                        'title' => 'Courtyard Signal',
                        'description' => 'Planning room for projection cues, field recordings, and light timing.',
                        'topic' => 'Projection notes and field recordings',
                        'image' => '/images/live-rooms/courtyard-signal.jpg',
                        'status' => 'scheduled',
                        'listeners_count' => 18,
                        'speakers_count' => 2,
                        'started_at' => null,
                        'ended_at' => null,
                        'audio_url' => null,
                        'waveform' => null,
                        'tags' => ['projection', 'field recording'],
                        'is_featured' => false,
                        'is_active' => true,
                    ],
                ),
                'night-archive' => LiveRoom::updateOrCreate(
                    ['city_id' => $city->id, 'slug' => 'night-archive'],
                    [
                        'district_id' => $districts['pigneto']->id,
                        'host_id' => $users['neri@novera.test']->id,
                        'artist_profile_id' => $profiles['neri-luce']->id,
                        'event_id' => $events['afterlight-studies-event']->id,
                        'space_id' => $spaces['pigneto-archive']->id,
                        'title' => 'Night Archive',
                        'description' => 'Moving-image references and rough edits for tonight’s screening.',
                        'topic' => 'Moving image references for tonight',
                        'image' => '/images/live-rooms/night-archive.jpg',
                        'status' => 'live',
                        'listeners_count' => 31,
                        'speakers_count' => 4,
                        'started_at' => $now->copy()->subMinutes(32),
                        'ended_at' => null,
                        'audio_url' => '/audio/night-archive.mp3',
                        'waveform' => [18, 30, 22, 36, 28, 46, 40, 51, 37, 44],
                        'tags' => ['moving image', 'archive'],
                        'is_featured' => false,
                        'is_active' => true,
                    ],
                ),
            ]);

            $openCalls = collect([
                'light-artist-for-live-score' => OpenCall::updateOrCreate(
                    ['city_id' => $city->id, 'slug' => 'light-artist-for-live-score'],
                    [
                        'district_id' => $districts['san-lorenzo']->id,
                        'collective_id' => null,
                        'event_id' => $events['courtyard-resonance-event']->id,
                        'space_id' => $spaces['cava-studio']->id,
                        'creator_id' => $users['luca@novera.test']->id,
                        'title' => 'Light artist for live score',
                        'description' => 'Seeking a light artist to shape a responsive projection and DMX score.',
                        'role_needed' => 'Light artist',
                        'discipline' => 'Projection / DMX',
                        'image' => '/images/open-calls/light-artist-live-score.jpg',
                        'deadline_at' => $now->copy()->addDays(3)->setTime(18, 0),
                        'reward_type' => 'paid',
                        'reward_details' => 'Budget 800 EUR',
                        'location_mode' => 'in person',
                        'urgency' => 'closing soon',
                        'status' => 'open',
                        'applicants_count' => 6,
                        'tags' => ['projection', 'dmx', 'live score'],
                        'requirements' => ['DMX experience', 'available for rehearsal in San Lorenzo'],
                        'is_featured' => true,
                        'is_active' => true,
                    ],
                ),
                'field-recordings-archive' => OpenCall::updateOrCreate(
                    ['city_id' => $city->id, 'slug' => 'field-recordings-archive'],
                    [
                        'district_id' => $districts['ostiense']->id,
                        'collective_id' => $collectives['echoes-of-now']->id,
                        'event_id' => $events['ruins-in-frequency']->id,
                        'space_id' => $spaces['forma-cinema']->id,
                        'creator_id' => $users['alba@novera.test']->id,
                        'title' => 'Field recordings archive',
                        'description' => 'Collecting new field recordings for a shared Ostiense listening archive.',
                        'role_needed' => 'Sound artists',
                        'discipline' => 'Field recording',
                        'image' => '/images/open-calls/field-recordings-archive.jpg',
                        'deadline_at' => $now->copy()->addDays(10)->setTime(12, 0),
                        'reward_type' => 'residency',
                        'reward_details' => '5 places available',
                        'location_mode' => 'hybrid',
                        'urgency' => 'new',
                        'status' => 'open',
                        'applicants_count' => 11,
                        'tags' => ['sound', 'archive', 'field recording'],
                        'requirements' => ['portable recorder', 'short audio note'],
                        'is_featured' => true,
                        'is_active' => true,
                    ],
                ),
                'brand-identity-for-collective' => OpenCall::updateOrCreate(
                    ['city_id' => $city->id, 'slug' => 'brand-identity-for-collective'],
                    [
                        'district_id' => $districts['testaccio']->id,
                        'collective_id' => $collectives['echoes-of-now']->id,
                        'event_id' => null,
                        'space_id' => null,
                        'creator_id' => $users['alba@novera.test']->id,
                        'title' => 'Brand identity for collective',
                        'description' => 'Echoes Of Now needs a visual identity system for posters, rooms, and releases.',
                        'role_needed' => 'Visual designer',
                        'discipline' => 'Identity / strategy',
                        'image' => '/images/open-calls/brand-identity-collective.jpg',
                        'deadline_at' => $now->copy()->addDays(14)->setTime(17, 0),
                        'reward_type' => 'paid',
                        'reward_details' => 'Budget 1800 EUR',
                        'location_mode' => 'remote',
                        'urgency' => 'new',
                        'status' => 'open',
                        'applicants_count' => 9,
                        'tags' => ['identity', 'design', 'collective'],
                        'requirements' => ['portfolio', 'brand system experience'],
                        'is_featured' => false,
                        'is_active' => true,
                    ],
                ),
                'moving-image-installation' => OpenCall::updateOrCreate(
                    ['city_id' => $city->id, 'slug' => 'moving-image-installation'],
                    [
                        'district_id' => $districts['pigneto']->id,
                        'collective_id' => $collectives['afterlight-studies']->id,
                        'event_id' => $events['afterlight-studies-event']->id,
                        'space_id' => $spaces['pigneto-archive']->id,
                        'creator_id' => $users['neri@novera.test']->id,
                        'title' => 'Moving image installation',
                        'description' => 'Afterlight Studies is looking for an editor/colorist for a short-term installation.',
                        'role_needed' => 'Editor / colorist',
                        'discipline' => 'Moving image',
                        'image' => '/images/open-calls/moving-image-installation.jpg',
                        'deadline_at' => $now->copy()->addDays(5)->setTime(20, 0),
                        'reward_type' => 'paid',
                        'reward_details' => 'Short-term commission',
                        'location_mode' => 'hybrid',
                        'urgency' => 'urgent',
                        'status' => 'open',
                        'applicants_count' => 4,
                        'tags' => ['editing', 'color', 'installation'],
                        'requirements' => ['editing reel', 'DaVinci Resolve preferred'],
                        'is_featured' => false,
                        'is_active' => true,
                    ],
                ),
            ]);

            $activities = [
                [
                    'type' => 'live_room_started',
                    'title' => 'Alba Forma started a listening session',
                    'description' => 'Travertine Echoes is live from Ostiense with dusk recordings.',
                    'tone' => 'audio',
                    'subject' => $liveRooms['travertine-echoes'],
                    'user' => $users['alba@novera.test'],
                    'artist' => $profiles['alba-forma'],
                    'district' => $districts['ostiense'],
                    'occurred_at' => $now->copy()->subMinutes(22),
                    'metadata' => ['listeners' => 42],
                    'is_featured' => true,
                ],
                [
                    'type' => 'open_call_created',
                    'title' => 'Cava Studio posted a collaboration request',
                    'description' => 'A light artist is needed for a live score in San Lorenzo.',
                    'tone' => 'opportunities',
                    'subject' => $openCalls['light-artist-for-live-score'],
                    'user' => $users['luca@novera.test'],
                    'artist' => $profiles['luca-moretti'],
                    'district' => $districts['san-lorenzo'],
                    'occurred_at' => $now->copy()->subMinutes(47),
                    'metadata' => ['reward_type' => 'paid'],
                    'is_featured' => true,
                ],
                [
                    'type' => 'artist_work_uploaded',
                    'title' => 'Neri Luce uploaded moving-image work',
                    'description' => 'New fragments from the Night Archive screening notes are available.',
                    'tone' => 'artists',
                    'subject' => $profiles['neri-luce'],
                    'user' => $users['neri@novera.test'],
                    'artist' => $profiles['neri-luce'],
                    'district' => $districts['pigneto'],
                    'occurred_at' => $now->copy()->subHour(),
                    'metadata' => ['format' => '16mm reference'],
                    'is_featured' => false,
                ],
                [
                    'type' => 'artist_joined',
                    'title' => 'Riva Ensemble joined the Rome scene',
                    'description' => 'The performance collective is open to movement-led collaborations.',
                    'tone' => 'artists',
                    'subject' => $profiles['riva-ensemble'],
                    'user' => $users['riva@novera.test'],
                    'artist' => $profiles['riva-ensemble'],
                    'district' => $districts['trastevere'],
                    'occurred_at' => $now->copy()->subHours(2),
                    'metadata' => ['status' => 'recruiting'],
                    'is_featured' => false,
                ],
                [
                    'type' => 'event_created',
                    'title' => 'Ruins in Frequency was published',
                    'description' => 'A spatial audio session is scheduled tonight at Forma Cinema.',
                    'tone' => 'events',
                    'subject' => $events['ruins-in-frequency'],
                    'user' => $users['alba@novera.test'],
                    'artist' => $profiles['alba-forma'],
                    'district' => $districts['ostiense'],
                    'occurred_at' => $now->copy()->subHours(3),
                    'metadata' => ['starts_at' => $events['ruins-in-frequency']->starts_at?->toISOString()],
                    'is_featured' => true,
                ],
                [
                    'type' => 'collective_recruiting',
                    'title' => 'Echoes Of Now started recruiting',
                    'description' => 'The audio-visual collective is looking for new night-culture collaborators.',
                    'tone' => 'collectives',
                    'subject' => $collectives['echoes-of-now'],
                    'user' => $users['alba@novera.test'],
                    'artist' => $profiles['alba-forma'],
                    'district' => $districts['testaccio'],
                    'occurred_at' => $now->copy()->subHours(4),
                    'metadata' => ['members_count' => 18],
                    'is_featured' => false,
                ],
                [
                    'type' => 'space_available',
                    'title' => 'Forma Cinema became available tonight',
                    'description' => 'The cinema has capacity for 120 people and spatial audio support.',
                    'tone' => 'spaces',
                    'subject' => $spaces['forma-cinema'],
                    'user' => $users['alba@novera.test'],
                    'artist' => $profiles['alba-forma'],
                    'district' => $districts['ostiense'],
                    'occurred_at' => $now->copy()->subHours(5),
                    'metadata' => ['capacity' => 120],
                    'is_featured' => true,
                ],
                [
                    'type' => 'ai_match_created',
                    'title' => 'AI Match found 3 recommendations for Luca',
                    'description' => 'New matches include an open call, an event, and a sound artist.',
                    'tone' => 'match',
                    'subject' => $profiles['luca-moretti'],
                    'user' => $users['luca@novera.test'],
                    'artist' => $profiles['luca-moretti'],
                    'district' => $districts['san-lorenzo'],
                    'occurred_at' => $now->copy()->subHours(6),
                    'metadata' => ['recommendations' => 3],
                    'is_featured' => false,
                ],
            ];

            foreach ($activities as $activity) {
                Activity::updateOrCreate(
                    ['type' => $activity['type'], 'title' => $activity['title']],
                    [
                        'city_id' => $city->id,
                        'district_id' => $activity['district']->id,
                        'user_id' => $activity['user']->id,
                        'artist_profile_id' => $activity['artist']->id,
                        'subject_type' => $activity['subject']->getMorphClass(),
                        'subject_id' => $activity['subject']->id,
                        'description' => $activity['description'],
                        'metadata' => $activity['metadata'],
                        'tone' => $activity['tone'],
                        'occurred_at' => $activity['occurred_at'],
                        'is_public' => true,
                        'is_featured' => $activity['is_featured'],
                    ],
                );
            }

            $matches = [
                [
                    'title' => 'Light artist for live score',
                    'reason' => 'Your projection mapping and stage visuals fit this paid Cava Studio request.',
                    'score' => 92,
                    'category' => 'open_call',
                    'status' => 'new',
                    'matchable' => $openCalls['light-artist-for-live-score'],
                ],
                [
                    'title' => 'Ruins in Frequency',
                    'reason' => 'A spatial audio session that needs visual atmosphere and projection language.',
                    'score' => 88,
                    'category' => 'event',
                    'status' => 'saved',
                    'matchable' => $events['ruins-in-frequency'],
                ],
                [
                    'title' => 'Alba Forma',
                    'reason' => 'Alba is live now and shares your interest in stage-responsive sensory work.',
                    'score' => 84,
                    'category' => 'artist',
                    'status' => 'new',
                    'matchable' => $profiles['alba-forma'],
                ],
                [
                    'title' => 'Forma Cinema',
                    'reason' => 'A flexible cinema space with the audio setup your visual installations can respond to.',
                    'score' => 76,
                    'category' => 'space',
                    'status' => 'viewed',
                    'matchable' => $spaces['forma-cinema'],
                ],
            ];

            foreach ($matches as $match) {
                AiMatch::updateOrCreate(
                    [
                        'user_id' => $users['luca@novera.test']->id,
                        'title' => $match['title'],
                    ],
                    [
                        'artist_profile_id' => $profiles['luca-moretti']->id,
                        'city_id' => $city->id,
                        'district_id' => $districts['san-lorenzo']->id,
                        'matchable_type' => $match['matchable']->getMorphClass(),
                        'matchable_id' => $match['matchable']->id,
                        'reason' => $match['reason'],
                        'score' => $match['score'],
                        'category' => $match['category'],
                        'tone' => 'match',
                        'status' => $match['status'],
                        'metadata' => ['source' => 'local_seed', 'profile_slug' => 'luca-moretti'],
                        'expires_at' => $now->copy()->addWeeks(2),
                    ],
                );
            }
        });
    }
}
